#!/bin/bash
# setup-rclone.sh — Configure rclone for Alibaba Cloud OSS with encryption
# Usage: ./setup-rclone.sh --endpoint ENDPOINT --bucket BUCKET --ak AK --sk SK [--config-path PATH]
#
# This script creates an rclone configuration file with:
#   1. A raw OSS remote (S3-compatible)
#   2. A crypt remote wrapping the OSS remote for client-side encryption

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
CONFIG_PATH=""
ENDPOINT=""
BUCKET=""
ACCESS_KEY_ID=""
ACCESS_KEY_SECRET=""
REMOTE_NAME="oss-crypt"
RAW_REMOTE_NAME="oss-raw"

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --endpoint)       ENDPOINT="$2";       shift 2 ;;
        --bucket)         BUCKET="$2";         shift 2 ;;
        --ak)             ACCESS_KEY_ID="$2";  shift 2 ;;
        --sk)             ACCESS_KEY_SECRET="$2"; shift 2 ;;
        --config-path)    CONFIG_PATH="$2";    shift 2 ;;
        --remote-name)    REMOTE_NAME="$2";    shift 2 ;;
        -h|--help)
            echo "Usage: $0 --endpoint ENDPOINT --bucket BUCKET --ak AK --sk SK [--config-path PATH]"
            exit 0 ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1 ;;
    esac
done

# ---------------------------------------------------------------------------
# Validate required arguments
# ---------------------------------------------------------------------------
missing=()
[[ -z "$ENDPOINT" ]]       && missing+=("--endpoint")
[[ -z "$BUCKET" ]]         && missing+=("--bucket")
[[ -z "$ACCESS_KEY_ID" ]]  && missing+=("--ak")
[[ -z "$ACCESS_KEY_SECRET" ]] && missing+=("--sk")

if [[ ${#missing[@]} -gt 0 ]]; then
    echo "ERROR: Missing required arguments: ${missing[*]}" >&2
    echo "Usage: $0 --endpoint ENDPOINT --bucket BUCKET --ak AK --sk SK" >&2
    exit 1
fi

# Default config path
if [[ -z "$CONFIG_PATH" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    CONFIG_PATH="${SCRIPT_DIR}/../data/rclone.conf"
fi

# ---------------------------------------------------------------------------
# Check rclone availability
# ---------------------------------------------------------------------------
RCLONE="${RCLONE:-rclone}"
if ! command -v "$RCLONE" &>/dev/null; then
    echo "ERROR: rclone not found in PATH. Please install rclone first." >&2
    echo "  curl https://rclone.org/install.sh | sudo bash" >&2
    exit 1
fi

echo "Using rclone: $($RCLONE version 2>&1 | head -1)"

# ---------------------------------------------------------------------------
# Generate encryption passwords
# ---------------------------------------------------------------------------
echo "Generating encryption passwords..."

# Primary password (used to derive the data encryption key)
PASSWORD=$("$RCLONE" obscure "$(openssl rand -base64 32)")
if [[ $? -ne 0 ]]; then
    echo "ERROR: Failed to generate obscured password" >&2
    exit 1
fi

# Salt/password2 (used for filename encryption)
PASSWORD2=$("$RCLONE" obscure "$(openssl rand -base64 32)")
if [[ $? -ne 0 ]]; then
    echo "ERROR: Failed to generate obscured salt" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Write rclone configuration
# ---------------------------------------------------------------------------
CONFIG_DIR="$(dirname "$CONFIG_PATH")"
mkdir -p "$CONFIG_DIR"

# Backup existing config if present
if [[ -f "$CONFIG_PATH" ]]; then
    BACKUP="${CONFIG_PATH}.backup.$(date +%Y%m%d%H%M%S)"
    cp "$CONFIG_PATH" "$BACKUP"
    echo "Backed up existing config to: $BACKUP"
fi

cat > "$CONFIG_PATH" <<EOF
# Rclone configuration for NAS backup to Alibaba Cloud OSS
# Generated by setup-rclone.sh on $(date -Iseconds)
# WARNING: This file contains encrypted credentials. Keep it secure!

[${RAW_REMOTE_NAME}]
type = s3
provider = AlibabaOss
endpoint = ${ENDPOINT}
access_key_id = ${ACCESS_KEY_ID}
secret_access_key = ${ACCESS_KEY_SECRET}
acl = private
storage_class = COLD_ARCHIVE

[${REMOTE_NAME}]
type = crypt
remote = ${RAW_REMOTE_NAME}:${BUCKET}
password = ${PASSWORD}
password2 = ${PASSWORD2}
filename_encryption = standard
directory_name_encryption = true
EOF

# Set restrictive permissions
chmod 600 "$CONFIG_PATH"

echo ""
echo "========================================="
echo "  Rclone configuration created successfully"
echo "========================================="
echo ""
echo "  Config file:  ${CONFIG_PATH}"
echo "  Raw remote:   ${RAW_REMOTE_NAME}"
echo "  Crypt remote: ${REMOTE_NAME}"
echo "  Bucket:       ${BUCKET}"
echo ""
echo "  IMPORTANT: Save the encryption passwords in a secure offline location!"
echo "  If you lose them, you will NOT be able to recover your encrypted data."
echo ""

# ---------------------------------------------------------------------------
# Verify configuration
# ---------------------------------------------------------------------------
echo "Verifying rclone configuration..."
if "$RCLONE" config show --config "$CONFIG_PATH" &>/dev/null; then
    echo "✓ Configuration is valid"
else
    echo "⚠ Configuration verification failed. Please check the config file manually."
fi

echo ""
echo "To test connectivity, run:"
echo "  rclone lsd ${REMOTE_NAME}: --config ${CONFIG_PATH}"
